name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint-nofix

      - name: Unit test
        run: npm run unit

      - name: E2E test
        run: npm run e2e
